version: '2.1'

services:
  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    networks:
      - servers
    depends_on:
      - server1
      - server2
      - server3
      - balancer
      - database
    environment: 
      CONF_RESPONSE_DELAY_SEC: 2

  balancer:
    command: ["lb", "--trace=true"]
