version: '2.1'

networks:
  servers:

services:
  
  database:
    build: .
    command: "db"
    networks:
      - servers
    ports:
      - "18080:18080"

  balancer:
    build: .
    depends_on: 
      - database
    command: "lb --trace"
    networks:
      - servers
    ports:
      - "8090:8090"

  server1:
    build: .
    depends_on: 
      - database
    networks:
      - servers
    ports:
      - "8080:8080"

  server2:
    build: .
    depends_on: 
      - database
    networks:
      - servers
    ports:
      - "8081:8080"

  server3:
    build: .
    depends_on: 
      - database
    networks:
      - servers
    ports:
      - "8082:8080"
